### ISSUE TITLE
Top of page should be more driven towards call to action

### ISSUE THREAD

**Issue by martincollignon** [Jacse/worlds-best-climate-plan#1]
Idé:
- Titel
- Undertitel
- To CTA'er: [Støt som organisation] [Støt som borgere]
- Carrousel med organisationer
- Carousel med [as seen in] med medier

Læs om løsningen...
---
Faktaboks

---

Lang version

--- 

FAQ

**Comment by Jacse** [comment]
Hvad tænker vi der sker når man trykker på 'støt'-knapperne?

**Comment by martincollignon** [comment]
Corporate: måske en form pop-up med virksomhedsnavn, email?
Borger: hvis NGO'er går om bord skal vi 100p have borgerforslag. Ellers en form pop-up med navn, email og by?

**Comment by Jacse** [comment]
Som så skal indsamles i en database som vi kan bruge til nyhedsbrev osv?

**Comment by Jacse** [comment]
Hvilke organisationer og medier skal vi nævne? Vil vi lave logoerne til links, der linker til en relevant side/artikel?

**Comment by martincollignon** [comment]
Organisationer = NGO'er, tænketank, virksomheder. Vi kan allerede få Klimabevægelsen, Ungeklimarådet (ingen logo), Det Grønne Studenterbevægelse og Citizens Climate Lobby.

Yup, det synes jeg :D

Vi har ingen

**Comment by Jacse** [comment]
Closing this with newest version
