### ISSUE TITLE
Style buttons

### ISSUE THREAD

**Issue by Jacse** [Jacse/worlds-best-climate-plan#10]
Buttons need a loving hand

**Comment by Jacse** [comment]
![ScreenRecording2019-12-31at08074](https://user-images.githubusercontent.com/3637499/71613180-25ae4e80-2ba5-11ea-9943-37779969d941.gif)

Example one

**Comment by Jacse** [comment]
We could also consider adding icons to the two CTA buttons

**Comment by martincollignon** [comment]
> We could also consider adding icons to the two CTA buttons

Yes - maybe a pen ?

**Comment by martincollignon** [comment]
https://uicookies.com/css-buttons/
