### ISSUE TITLE
Add a form when "Støt som ..." is pressed

### ISSUE THREAD

**Issue by martincollignon** [Jacse/worlds-best-climate-plan#16]
textfield: [first name]
textfield: [last name]
textfield: [organisation] -- optional
emailfield: [email]
checkbox: Ja, vil jeg gerne støtte Verdens bedste klimaplan
checkbox: Jeg vil gerne få opdateringer fra Verdens bedste klimaplan

At submission the screens should change to "Tak - tjek din email for at bekræfte din støtte"

Submission should hook up to Mailgun

**Comment by Jacse** [comment]
Vi skal måske genoverveje wording på "Ja, vil jeg gerne støtte Verdens bedste klimaplan" - det er ret vagt og jeg ville ikke rigtig vide hvad jeg skrev mig op til.

Har du API adgang til Mailgun?

**Comment by martincollignon** [comment]
Wording skal helt klart ændres :) Du har login info på Slack ;)

**Comment by martincollignon** [comment]
https://jaredpalmer.com/formik kan måske hjælpe?
