### ISSUE TITLE
Add a "hidden" page "/econstatement"

### ISSUE THREAD

**Issue by martincollignon** [Jacse/worlds-best-climate-plan#31]
Content:

- https://docs.google.com/document/d/1SGSxH34PSrsHAw1XWWXrfSTGb7B_uP2u87fmTae8bPY/edit

- <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSf-wtAyJBnTpPggT2-OSzW64FFnhG20ajBHAFQZwAEjJGC-HA/viewform?embedded=true" width="640" height="1187" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

**Comment by Jacse** [comment]
Why hidden? To limit signups by non-professors and reduce work in confirming credentials?

**Comment by Jacse** [comment]
Closed in favour of #40

**Comment by martincollignon** [comment]
Yup - may make it public once we have enough signatures.
