### ISSUE TITLE
Move content around

### ISSUE THREAD

**Issue by martincollignon** [Jacse/worlds-best-climate-plan#41]
Index:

- Replace the 1,2,3 with 

[Verdens bedste klimaplan.docx](https://github.com/Jacse/worlds-best-climate-plan/files/4036495/Verdens.bedste.klimaplan.docx)

- Remove FAQ

The-plan

- Add 1,2,3 ahead of the long form
- Move FAQ below the long form

**Comment by Jacse** [comment]
"Add 1,2,3 ahead of the long form" is that the current "1,2,3" or the new ones from the word-doc?

**Comment by martincollignon** [comment]
that is the current one.

**Comment by Jacse** [comment]
Har vi nogle illustration el lign til det tekst? Kunne godt være bange for at det blev lidt tekststungt..

**Comment by martincollignon** [comment]
Vi har #6 ? Hvad tænker du?
