### ISSUE TITLE
Component: Letter

### ISSUE THREAD

**Issue by madsnedergaard** [Jacse/worlds-best-climate-plan#47]
## Todo

- [x] Create and style component
- [x] Get updated copy

**Comment by Jacse** [comment]
Jeg tror ikke @martincollignon skal stå som afsender. [I det nyeste design](https://sketch.cloud/s/3WEbm/a/oPqGVx/play) er han fjernet.

**Comment by martincollignon** [comment]
Ja tak. Jeg kan faktisk ikke engang skrive under borgerforslaget pga.
statsborgerskab :D
