### ISSUE TITLE
Create and implement Borgerforslag scraper

### ISSUE THREAD

**Issue by madsnedergaard** [Jacse/worlds-best-climate-plan#56]
## Todo

- [x] Create a cloud function that scrapes the Borgerforslag page and fetches amount of votes
- [x] Call function from website and show result in header

**Comment by magnuspaaske** [comment]
What kind of backend do we have? Could set it up on with Heroku potentially

**Comment by martincollignon** [comment]
We're running on gcloud so this could just be a cloud function 😎 on which
address should I give you access?

**Comment by madsnedergaard** [comment]
Did you do any work on this, @magnuspaaske? :)

**Comment by magnuspaaske** [comment]
Not yet. Twitter PM'ing my email

**Comment by magnuspaaske** [comment]
Code is here: https://console.cloud.google.com/functions/details/us-central1/scrapeSignatures
API endpoint is here: https://us-central1-boxwood-academy-251913.cloudfunctions.net/scrapeSignatures

Basically just need to update the code with the borgerforslag ID.

**Comment by magnuspaaske** [comment]
Not sure I can directly close this issue here, but consider it solved

**Comment by magnuspaaske** [comment]
Although where should we put the counter? I'm thinking like this on the frontpage

<img width="827" alt="Screenshot 2020-03-02 at 12 43 32" src="https://user-images.githubusercontent.com/1206122/75673549-7f092b80-5c83-11ea-9b0c-5542bfaaf37f.png">

**Comment by Jacse** [comment]
According to the design in [Zeplin](https://app.zeplin.io/project/5e46a5b89c28aeae44d52a20/screen/5e51ac43ff4f2f6494ddbab5) it should be in the menu next to the main button.

**Comment by Jacse** [comment]
@magnuspaaske would it be possible to cache the number of backers? Requests are a little slow.

**Comment by magnuspaaske** [comment]
I'm thinking about ways to cache the number on the site and working on getting it to show in the corner like the design

**Comment by Jacse** [comment]
> I'm thinking about ways to cache the number on the site and working on getting it to show in the corner like the design

Sounds good. I've already implemented the front-end component

**Comment by magnuspaaske** [comment]
Oh dang, otherwise it's also here: https://github.com/Jacse/worlds-best-climate-plan/pull/69

**Comment by Jacse** [comment]
Closing this since the component has been created. I'll create a new issue for the back-end caching
