### ISSUE TITLE
Add social buttons below main cta

### ISSUE THREAD

**Issue by martincollignon** [Jacse/worlds-best-climate-plan#65]
Should just link to the borgerforslag itself, just like Borgerforslag does it: 
- Share on Linkedin (https://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fwww.borgerforslag.dk%2Fse-og-stoet-forslag%2F%3FId%3DFT-02233)
- Share on FB (https://www.facebook.com/sharer.php?u=https%3A%2F%2Fwww.borgerforslag.dk%2Fse-og-stoet-forslag%2F%3FId%3DFT-02233)
- Share on Twitter (https://twitter.com/share?url=https%3A%2F%2Fwww.borgerforslag.dk%2Fse-og-stoet-forslag%2F%3FId%3DFT-02233&text=Dansk%20klimalov%20nu)
- Share on email (mailto link)

The buttons should be more subtle than sign-up (or even be greyed out before you click on the Sign-up if possible).

We could even do like on borgerforslag on mobile where a share button appears from the bottom: https://www.borgerforslag.dk/se-og-stoet-forslag/?Id=FT-02233

**Comment by magnuspaaske** [comment]
Working on it

**Comment by magnuspaaske** [comment]
See https://github.com/Jacse/worlds-best-climate-plan/pull/67
