### ISSUE TITLE
Create quick fact box

### ISSUE THREAD

**Issue by Jacse** [Jacse/worlds-best-climate-plan#7]
What contents do we want in the fact-box?

**Comment by martincollignon** [comment]
Verdens bedste klimaplan sørger for, at det bliver nemmere at være klimavenlig. Her er hvad planen består af:
- Forureneren betaler når forureningen sker. Der skal være en støt stigende pris på de få hovedkilder til drivhusgasudledninger, fx. ved forbrænding af fossile brændsler
- Hele indtægten bliver delt tilbage til danskerne i lige dele, så den gennemsnitlige dansker ikke skal have penge op af lommen
- Virksomheder, der er mere konkurrenceudsatte kan blive kompenseret

What say you?

**Comment by Jacse** [comment]
Closing with newest version
