### ISSUE TITLE
Questions on FAQ don't "close"

### ISSUE THREAD

**Issue by martincollignon** [Jacse/worlds-best-climate-plan#81]

**Comment by magnuspaaske** [comment]
Jeg tjekkede det lige og det ser ud til at det fungerer når man kører det med `yarn start` og den bygger til development mode. Når man bygger det med `yarn build` og bruger `yarn serve` får man fejlen. Så det er nok et build issue

**Comment by martincollignon** [comment]
@Jacse kan du tjekke?
