### ISSUE TITLE
Style FAQ-section

### ISSUE THREAD

**Issue by Jacse** [Jacse/worlds-best-climate-plan#9]
The FAQ section needs a little touching up.

**Comment by martincollignon** [comment]
http://bentographics.com/site/wp-content/uploads/projects/flutterscape/FlutterScape-faq-page.gif

**Comment by martincollignon** [comment]
https://dribbble.com/shots/3944298-FAQ-Daily-UI-092?utm_source=Pinterest_Shot&utm_campaign=arunmalavan&utm_content=FAQ-%20Daily%20UI::%20%23092&utm_medium=Social_Share

**Comment by martincollignon** [comment]
https://dribbble.com/shots/5658483-FAQ
